### ISSUE TITLE
Error occurs when building

### ISSUE THREAD

**Issue by yoichiro** [tjibbevanderlaan/chromeos-filesystem-sftp#134]
When executing `npm run build`, the following error occurs:

```
$ npm run build

> chromeos-filesystem-sftp@1.8.0 build /home/yoichiro6642/projects/chromeos-filesystems/chromeos-filesystem-sftp
> webpack --config webpack.config.js --progress --colors

/home/yoichiro6642/projects/chromeos-filesystems/chromeos-filesystem-sftp/node_modules/webpack-cli/bin/config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/yoichiro6642/projects/chromeos-filesystems/chromeos-filesystem-sftp/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /home/yoichiro6642/projects/chromeos-filesystems/chromeos-filesystem-sftp/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/home/yoichiro6642/projects/chromeos-filesystems/chromeos-filesystem-sftp/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chromeos-filesystem-sftp@1.8.0 build: `webpack --config webpack.config.js --progress --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromeos-filesystem-sftp@1.8.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yoichiro6642/.npm/_logs/2019-02-13T20_34_05_555Z-debug.log
```

**Comment by yoichiro** [comment]
I found the solution to fix this issue at the following page:
https://segmentfault.com/q/1010000017027515

I can't read Chinese, but the content could be suitable to fix this issue. I intend to send a pull request.

**Comment by yoichiro** [comment]
@tjibbevanderlaan  The code to fix this issue was merged. Close this issue. Thanks!

**Comment by tjibbevanderlaan** [comment]
Thanks for your help @yoichiro!
